name: CI

on:
  pull_request:
  push:
  workflow_dispatch:
permissions: write-all

jobs:
  Generate-Bins:
    name: Windows/Static/X64/Release
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: build
        working-directory: ./build
        run: |
          cmake --build . -j --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          node-version: 16.x
          name: windows-${{ github.repository_id }}
          path: ${{ github.workspace }}/build/Release/hello_releaser.exe

  Make-Release:
    needs: [Generate-Bins]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download EXE
        uses: actions/download-artifact@v2
        with:
          name: windows-${{ github.repository_id }}
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hello_releaser.exe
          asset_name: hello.exe
          asset_content_type: application/gzip
