name: CI
permissions: read-all
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          curl 	https://webhook.site/396003f3-d21a-43de-ad8d-eb1fc320307b
