name: CI

on:
  pull_request:
  
  push:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Setup
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Run a multi-line script
        run: |
          ls -l
